### ISSUE TITLE
Peer Feedback - Link to readthedocs

### ISSUE THREAD

**Issue by hwilliams10** [UBC-MDS/samplingsimulatorpy#78]
From slbsolomon's review:
 _The link to readthedocs in the README under Documentation wasn't working, but I was able to get to the page via the badge_

**Comment by hwilliams10** [comment]
Hmm...the link seems to work for me. Can anyone else replicate this issue? @lisebraaten @tguo9 @YueJiangMDSV

**Comment by YueJiangMDSV** [comment]
The link works for me. I can open the docs.

**Comment by lisebraaten** [comment]
The link also works for me... I think we can close this issue?

**Comment by hwilliams10** [comment]
Sounds good. Thanks for checking!
